### ISSUE TITLE
opc_list.jl not found

### ISSUE THREAD

**Issue by hsucw** [hackjackhack/jia32#1]
Once I git pull the source, and I try to run the main.jl.
But it turned out to be an error 
"ERROR: LoadError: LoadError: LoadError: LoadError: could not open file /..../jia32/instr/opc_list.jl"

I found the op_list.jl is added into .git_ignore

Is it an mistake or should I do something more for correction ?

**Comment by hackjackhack** [comment]
From now on users have to 'make' to generate instruction jl files. I'll put his comment in README.md. This issue is closed.
